import SettingsProvider from "@/app/context";
import "@/app/globals.css";
import { auth } from "@/auth";
import AOSInitialize from "@/components/_global/aos-init";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ezinstaling.lol",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <SettingsProvider>
        <html lang="pl">
          <body className={poppins.className}>
            <NextTopLoader
              color="#ffbc04"
              height={4}
              zIndex={100}
              showSpinner={false}
            />
            {children}
          </body>
          <Analytics />
          <AOSInitialize />
        </html>
      </SettingsProvider>
    </SessionProvider>
  );
};

export default RootLayout;
